Added code of conduct
AlicanteFrontend/alicantefrontend.github.io pull request #20
Opened 2017-10-25 07:00 UTC by asierferro

Closes Issue #11

2017-10-25 08:02 UTC, AlvYuste reviewed
Enhorabuena, muy buena aportación.

2017-10-25 08:02 UTC, AlvYuste commented on CODE_OF_CONDUCT.md
> +Si cree que ha sido falsa o injustamente acusado de violar este código de conducta, debe notificarlo los organizadores de la comunidad, con una descripción concisa de su queja. Esta será gestionada d
falta un "**a** los organizadores"

2017-10-31 13:59 UTC, aarongarciah requested changes
Muchas gracias @asierferro 😄

¿Sería posible añadir el código de conducta también en inglés? Primero castellano y después inglés. Lo separaría con un `<hr>` (`---` en markdown).

2017-11-02 08:44 UTC, asierferro commented
Ok @aarongarciah,
Lo traduzco y lo subo.

2017-11-02 08:50 UTC, aarongarciah commented
Gracias @asierferro

2018-01-30 11:52 UTC, AlvYuste commented
Cómo va el estado de este PR? @asierferro

2018-01-30 13:36 UTC, asierferro commented
He traducido el código de conducta al Ingles @AlvYuste, quizas faltaría revisar la posibles faltas ortográficas antes de mergearlo.

2018-01-30 13:47 UTC, aarongarciah commented
He corregido un enlace y añadido el email y cuenta de Twitter en el apartado "Información de contacto". Gracias @asierferro

2018-01-30 14:45 UTC, AlvYuste approved these changes

2018-01-30 14:51 UTC, aarongarciah approved these changes

2018-01-30 14:52 UTC, merged